module.exports = [
    {
      app: "ROBLOX",
      category: "GAME",
      rating: 4.5,
      reviews: "4447388",
      size: "67M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone 10+",
      genres: "Adventure;Action & Adventure",
      last_updated: "July 31, 2018",
      current_ver: "2.347.225742",
      android_ver: "4.1 and up"
    },
    {
      app: "Subway Surfers",
      category: "GAME",
      rating: 4.5,
      reviews: "27722264",
      size: "76M",
      installs: "1,000,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone 10+",
      genres: "Arcade",
      last_updated: "July 12, 2018",
      current_ver: "1.90.0",
      android_ver: "4.1 and up"
    },
    {
      app: "Candy Crush Saga",
      category: "GAME",
      rating: 4.4,
      reviews: "22426677",
      size: "74M",
      installs: "500,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Casual",
      last_updated: "July 5, 2018",
      current_ver: "1.129.0.2",
      android_ver: "4.1 and up"
    },
    {
      app: "Solitaire",
      category: "GAME",
      rating: 4.7,
      reviews: "254258",
      size: "23M",
      installs: "10,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Card",
      last_updated: "August 1, 2018",
      current_ver: "2.137.0",
      android_ver: "4.1 and up"
    },
    {
      app: "Bubble Shooter",
      category: "GAME",
      rating: 4.5,
      reviews: "148897",
      size: "46M",
      installs: "10,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Casual",
      last_updated: "July 17, 2018",
      current_ver: "1.20.1",
      android_ver: "4.0.3 and up"
    },
    {
      app: "Hello Kitty Nail Salon",
      category: "GAME",
      rating: 4.2,
      reviews: "369203",
      size: "24M",
      installs: "50,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Casual;Pretend Play",
      last_updated: "April 17, 2018",
      current_ver: "1.5",
      android_ver: "4.1 and up"
    },
    {
      app: "slither.io",
      category: "GAME",
      rating: 4.4,
      reviews: "5234162",
      size: "Varies with device",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Action",
      last_updated: "November 14, 2017",
      current_ver: "Varies with device",
      android_ver: "2.3 and up"
    },
    {
      app: "Clash Royale",
      category: "GAME",
      rating: 4.6,
      reviews: "23133508",
      size: "97M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone 10+",
      genres: "Strategy",
      last_updated: "June 27, 2018",
      current_ver: "2.3.2",
      android_ver: "4.1 and up"
    },
    {
      app: "Temple Run 2",
      category: "GAME",
      rating: 4.3,
      reviews: "8118609",
      size: "62M",
      installs: "500,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Action",
      last_updated: "July 5, 2018",
      current_ver: "1.49.1",
      android_ver: "4.0 and up"
    },
    {
      app: "Pou",
      category: "GAME",
      rating: 4.3,
      reviews: "10485308",
      size: "24M",
      installs: "500,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Casual",
      last_updated: "May 25, 2018",
      current_ver: "1.4.77",
      android_ver: "4.0 and up"
    },
    {
      app: "Helix Jump",
      category: "GAME",
      rating: 4.2,
      reviews: "1497361",
      size: "33M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Action",
      last_updated: "April 9, 2018",
      current_ver: "1.0.6",
      android_ver: "4.1 and up"
    },
    {
      app: "Block Puzzle",
      category: "GAME",
      rating: 4.6,
      reviews: "59800",
      size: "7.8M",
      installs: "5,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Puzzle",
      last_updated: "March 6, 2018",
      current_ver: "2.9",
      android_ver: "2.3 and up"
    },
    {
      app: "Angry Birds Rio",
      category: "GAME",
      rating: 4.4,
      reviews: "2610526",
      size: "46M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Arcade",
      last_updated: "July 3, 2018",
      current_ver: "2.6.9",
      android_ver: "4.1 and up"
    },
    {
      app: "Plants vs. Zombies FREE",
      category: "GAME",
      rating: 4.4,
      reviews: "4066989",
      size: "69M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone 10+",
      genres: "Strategy",
      last_updated: "July 6, 2018",
      current_ver: "2.2.00",
      android_ver: "4.1 and up"
    },
    {
      app: "Sonic Dash",
      category: "GAME",
      rating: 4.5,
      reviews: "3778921",
      size: "75M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Arcade",
      last_updated: "July 26, 2018",
      current_ver: "3.8.5.Go",
      android_ver: "4.1 and up"
    },
    {
      app: "Candy Crush Soda Saga",
      category: "GAME",
      rating: 4.4,
      reviews: "6198563",
      size: "67M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Casual",
      last_updated: "July 10, 2018",
      current_ver: "1.118.4",
      android_ver: "4.1 and up"
    },
    {
      app: "Zombie Hunter King",
      category: "GAME",
      rating: 4.3,
      reviews: "10306",
      size: "50M",
      installs: "1,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Mature 17+",
      genres: "Action",
      last_updated: "August 1, 2018",
      current_ver: "1.0.8",
      android_ver: "2.3 and up"
    },
    {
      app: "Clash of Clans",
      category: "GAME",
      rating: 4.6,
      reviews: "44891723",
      size: "98M",
      installs: "100,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone 10+",
      genres: "Strategy",
      last_updated: "July 15, 2018",
      current_ver: "10.322.16",
      android_ver: "4.1 and up"
    },
    {
      app: "Kick the Buddy",
      category: "GAME",
      rating: 4.3,
      reviews: "1000417",
      size: "Varies with device",
      installs: "50,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Teen",
      genres: "Action",
      last_updated: "July 5, 2018",
      current_ver: "Varies with device",
      android_ver: "4.4 and up"
    },
    {
      app: "Block Puzzle Classic Legend !",
      category: "GAME",
      rating: 4.2,
      reviews: "17039",
      size: "4.9M",
      installs: "5,000,000+",
      type: "Free",
      price: "0",
      content_rating: "Everyone",
      genres: "Puzzle",
      last_updated: "April 13, 2018",
      current_ver: "2.9",
      android_ver: "2.3.3 and up"
    }
  ];